// SPDX-FileCopyrightText: 2024 - 2025 Simon Massey
// SPDX-License-Identifier: Apache-2.0
package com.github.trex_paxos.advisory_locks.server;

import java.time.Instant;

public sealed interface LockServerCommandValue {
  /// Try to acquire a lock with the given ID. If the lock is already held, this will fail.
  /// The stamp is not passed by the client rather it is generated by the server.
  record TryAcquireLock(
      String lockId,
      Instant expiryTime
  ) implements LockServerCommandValue {
  }

  record ReleaseLock(
      String lockId,
      long stamp
  ) implements LockServerCommandValue {
  }

  record GetLock(
      String lockId
  ) implements LockServerCommandValue {
  }
}
